### ISSUE TITLE
Seems great.. but..

### ISSUE THREAD

**Issue by akaAMAZING** [MassCraxx/PoeTradeHelper#1]
Hi there!

I have attempted to run this tool in Eclipse to no avail. I have added JavaFX library to the Build Path but it still encounters errors it seems.

How would you suggest I go about getting this up and running so I can give it a whirl and report back any issues?

Thank you.

**Comment by akaAMAZING** [comment]
Here is the current view:

http://prntscr.com/peelbb

**Comment by lmalvara** [comment]
> 
> 
> Here is the current view:
> 
> http://prntscr.com/peelbb

Hey its built using Python 3, Im unfamiliar with java. and I was using Pycharm IDE. The problem might be because your trying to build it in java instead of python?

**Comment by akaAMAZING** [comment]
How can you open this via Pycharm IDE lol?

It's written in Java...

**Comment by MassCraxx** [comment]
Hi, 
sorry for the late reply. I am not sure, but a lot of things have changed since the day you tried to build it.
I use IntelliJ and a relatively old java version to build, but it should work with any openjdk that has javafx included. No clue if this can work using Python...
